---
title: "TC_Strength_Sol"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(cowplot)
library(deSolve)
library(rstan)
library(coda)
library(modelbased)
library(shinystan)
library(colorspace)
library(bayesplot)
```

```{r}
setwd("~/Trophic_Cascade_Warming_Submission/Fitting Output/Draws")

DA_draws <- read.csv("DA_all_draws.csv")

HDA_draws <- read.csv("HDA_all_draws.csv")

```

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////// DEFINE ODE MODELS /////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

```{r}
DA_odemodel <- function(t, N, p) {
  dN1dt = (p[1]*N[1]*(1-N[1]*p[2]*exp(p[8]*t)))-(p[3]*N[1]*N[2]/(1+p[7]*(N[2]-0.003333333)+p[3]*p[6]*N[1])) #equation for resource
  dN2dt = (p[4]*p[3]*N[1]*N[2]/(1+p[7]*(N[2]-0.003333333)+p[3]*p[6]*N[1]))-p[5]*N[2] #equation for consumer
  return(list(c(dN1dt, dN2dt)))
}
```

```{r}
HDA_odemodel <- function(t, N, p) {
  dN1dt = (p[1]*N[1]*(1-N[1]*p[2]*exp(p[8]*t)))-(p[3]*N[1]*N[2]/(1+p[7]*(N[2]-0.003333333)+p[3]*p[6]*N[1]))
  
  dN2dt = ((p[4]*p[3]*N[1]*N[2])/((1+p[7]*(N[2]-0.003333333))+(p[3]*p[6]*N[1])))-((p[9]*N[2]*N[3])/((1+p[13]*(N[3]-0.003333333))+(p[9]*p[12]*N[2])))-(p[5]*N[2])
  
  dN3dt = ((p[10]*p[9]*N[2]*N[3])/((1+p[13]*(N[3]-0.003333333))+(p[9]*p[12]*N[2])))-(p[11]*N[3])
  
  return(list(c(dN1dt, dN2dt, dN3dt)))
}
```

CALCUYLATE AVERAGE INITIAL AMOUNG REPLICATRES PER ITERATION

```{r}
DA_draws <- DA_draws %>%
  rowwise() %>%
  mutate(N1_0_avg = mean(c(N1_0.1, N1_0.2, N1_0.3, N1_0.4, N1_0.5), na.rm = TRUE), 
         N2_0_avg = mean(c(N2_0.1, N2_0.2, N2_0.3, N2_0.4, N2_0.5), na.rm = TRUE))

HDA_draws <- HDA_draws %>%
  rowwise() %>%
  mutate(N1_0_avg = mean(c(N1_0.1, N1_0.2, N1_0.3, N1_0.4, N1_0.5), na.rm = TRUE), 
         N2_0_avg = mean(c(N2_0.1, N2_0.2, N2_0.3, N2_0.4, N2_0.5), na.rm = TRUE),
         N3_0_avg = mean(c(N3_0.1, N3_0.2, N3_0.3, N3_0.4, N3_0.5), na.rm = TRUE))
```


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////// SUBSAMPLE FIT DRAWS ///////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

```{r}
DA_14_draws_sample <- DA_draws %>% filter(Temp == 14) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

HDA_14_draws_sample <- HDA_draws %>% filter(Temp == 14) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

DA_17_draws_sample <- DA_draws %>% filter(Temp == 17) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

HDA_17_draws_sample <- HDA_draws %>% filter(Temp == 17) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

DA_20_draws_sample <- DA_draws %>% filter(Temp == 20) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

HDA_20_draws_sample <- HDA_draws %>% filter(Temp == 20) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

DA_23_draws_sample <- DA_draws %>% filter(Temp == 23) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

HDA_23_draws_sample <- HDA_draws %>% filter(Temp == 23) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

DA_26_draws_sample <- DA_draws %>% filter(Temp == 26) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)

HDA_26_draws_sample <- HDA_draws %>% filter(Temp == 26) %>% ungroup() %>% slice_sample(n  = 6000, replace = FALSE)
```



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////// CALCULATE SOLUTIONS FOR ALGAE  //////////////////////////////////////////////////////
////////////////////////////////////////////////////// WITHIN EACH TEMP AND TL TREATMENT /////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


```{r}
sol_DA_14 <- matrix(nrow=6000, ncol = 351)


for (i in 1:6000) {
sol_DA_14[i,] <- as.data.frame(lsoda(y = c(DA_14_draws_sample$N1_0_avg[i], 
                                           DA_14_draws_sample$N2_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = DA_odemodel,
                             parms = c(DA_14_draws_sample$r[i],
                                        DA_14_draws_sample$Q[i],
                                        DA_14_draws_sample$a1[i],
                                        DA_14_draws_sample$e1[i],
                                        DA_14_draws_sample$d1[i],
                                        DA_14_draws_sample$h1[i],
                                        DA_14_draws_sample$w1[i],
                                        DA_14_draws_sample$B[i])))[,2]
}
# divide this martix by the HDA matrix
```

```{r}
sol_HDA_14 <- matrix(nrow=6000, ncol = 351)


for (i in 1:6000) {
sol_HDA_14[i,] <- as.data.frame(lsoda(y = c(HDA_14_draws_sample$N1_0_avg[i], 
                                           HDA_14_draws_sample$N2_0_avg[i],
                                           HDA_14_draws_sample$N3_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = HDA_odemodel,
                             parms = c(HDA_14_draws_sample$r[i],
                                        HDA_14_draws_sample$Q[i],
                                        HDA_14_draws_sample$a1[i],
                                        5.447609e-04, #e1
                                        2.448435e+00, #d1
                                        HDA_14_draws_sample$h1[i],
                                        HDA_14_draws_sample$w1[i],
                                        1.811345e-02, #B 
                                       HDA_14_draws_sample$a2[i],
                                       HDA_14_draws_sample$e2[i],
                                       HDA_14_draws_sample$d2[i],
                                       HDA_14_draws_sample$h2[i],
                                       HDA_14_draws_sample$w2[i])))[,2]

}
```

```{r}
sol_DA_17 <- matrix(nrow=6000, ncol = 351)


for (i in 1:6000) {
sol_DA_17[i,] <- as.data.frame(lsoda(y = c(DA_17_draws_sample$N1_0_avg[i], 
                                           DA_17_draws_sample$N2_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = DA_odemodel,
                             parms = c(DA_17_draws_sample$r[i],
                                        DA_17_draws_sample$Q[i],
                                        DA_17_draws_sample$a1[i],
                                        DA_17_draws_sample$e1[i],
                                        DA_17_draws_sample$d1[i],
                                        DA_17_draws_sample$h1[i],
                                        DA_17_draws_sample$w1[i],
                                        DA_17_draws_sample$B[i])))[,2]
}
# divide this martix by the HDA matrix
```

```{r}
sol_HDA_17 <- matrix(nrow=6000, ncol = 351)

for (i in 1:6000) {
sol_HDA_17[i,] <- as.data.frame(lsoda(y = c(HDA_17_draws_sample$N1_0_avg[i], 
                                           HDA_17_draws_sample$N2_0_avg[i],
                                           HDA_17_draws_sample$N3_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = HDA_odemodel,
                             parms = c(HDA_17_draws_sample$r[i],
                                        HDA_17_draws_sample$Q[i],
                                        HDA_17_draws_sample$a1[i],
                                        2.455467e-05, # e1
                                        1.125211e+00, #d1
                                        HDA_17_draws_sample$h1[i],
                                        HDA_17_draws_sample$w1[i],
                                        7.995986e-02, #B 
                                       HDA_17_draws_sample$a2[i],
                                       HDA_17_draws_sample$e2[i],
                                       HDA_17_draws_sample$d2[i],
                                       HDA_17_draws_sample$h2[i],
                                       HDA_17_draws_sample$w2[i])))[,2]

}
```


```{r}
sol_DA_20 <- matrix(nrow=6000, ncol = 351)

for (i in 1:6000) {
sol_DA_20[i,] <- as.data.frame(lsoda(y = c(DA_20_draws_sample$N1_0_avg[i], 
                                           DA_20_draws_sample$N2_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = DA_odemodel,
                             parms = c(DA_20_draws_sample$r[i],
                                        DA_20_draws_sample$Q[i],
                                        DA_20_draws_sample$a1[i],
                                        DA_20_draws_sample$e1[i],
                                        DA_20_draws_sample$d1[i],
                                        DA_20_draws_sample$h1[i],
                                        DA_20_draws_sample$w1[i],
                                        DA_20_draws_sample$B[i])))[,2]
}

# divide this martix by the HDA matrix
```

```{r}
sol_HDA_20 <- matrix(nrow=6000, ncol = 351)

for (i in 1:6000) {
sol_HDA_20[i,] <- as.data.frame(lsoda(y = c(HDA_20_draws_sample$N1_0_avg[i], 
                                           HDA_20_draws_sample$N2_0_avg[i],
                                           HDA_20_draws_sample$N3_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = HDA_odemodel,
                             parms = c(HDA_20_draws_sample$r[i],
                                        HDA_20_draws_sample$Q[i],
                                        HDA_20_draws_sample$a1[i],
                                        4.437980e-05, # e1
                                        1.988016e+00, #d1
                                        HDA_20_draws_sample$h1[i],
                                        HDA_20_draws_sample$w1[i],
                                        8.957620e-02, #B 
                                       HDA_20_draws_sample$a2[i],
                                       HDA_20_draws_sample$e2[i],
                                       HDA_20_draws_sample$d2[i],
                                       HDA_20_draws_sample$h2[i],
                                       HDA_20_draws_sample$w2[i])))[,2]

}
```


```{r}
sol_DA_23 <- matrix(nrow=6000, ncol = 351)

for (i in 1:6000) {
sol_DA_23[i,] <- as.data.frame(lsoda(y = c(DA_23_draws_sample$N1_0_avg[i], 
                                           DA_23_draws_sample$N2_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = DA_odemodel,
                             parms = c(DA_23_draws_sample$r[i],
                                        DA_23_draws_sample$Q[i],
                                        DA_23_draws_sample$a1[i],
                                        DA_23_draws_sample$e1[i],
                                        DA_23_draws_sample$d1[i],
                                        DA_23_draws_sample$h1[i],
                                        DA_23_draws_sample$w1[i],
                                        DA_23_draws_sample$B[i])))[,2]
}

# divide this martix by the HDA matrix
```

```{r}
sol_HDA_23 <- matrix(nrow=6000, ncol = 351)

for (i in 1:6000) {
sol_HDA_23[i,] <- as.data.frame(lsoda(y = c(HDA_23_draws_sample$N1_0_avg[i], 
                                           HDA_23_draws_sample$N2_0_avg[i],
                                           HDA_23_draws_sample$N3_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = HDA_odemodel,
                             parms = c(HDA_23_draws_sample$r[i],
                                        HDA_23_draws_sample$Q[i],
                                        HDA_23_draws_sample$a1[i],
                                        1.021355e-05, # e1
                                        1.943547e+00, #d1
                                        HDA_23_draws_sample$h1[i],
                                        HDA_23_draws_sample$w1[i],
                                        7.738450e-02, #B 
                                       HDA_23_draws_sample$a2[i],
                                       HDA_23_draws_sample$e2[i],
                                       HDA_23_draws_sample$d2[i],
                                       HDA_23_draws_sample$h2[i],
                                       HDA_23_draws_sample$w2[i])))[,2]

}

```

```{r}
sol_DA_26 <- matrix(nrow=6000, ncol = 351)

for (i in 1:6000) {
sol_DA_26[i,] <- as.data.frame(lsoda(y = c(DA_26_draws_sample$N1_0_avg[i], 
                                           DA_26_draws_sample$N2_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = DA_odemodel,
                             parms = c(DA_26_draws_sample$r[i],
                                        DA_26_draws_sample$Q[i],
                                        DA_26_draws_sample$a1[i],
                                        DA_26_draws_sample$e1[i],
                                        DA_26_draws_sample$d1[i],
                                        DA_26_draws_sample$h1[i],
                                        DA_26_draws_sample$w1[i],
                                        DA_26_draws_sample$B[i])))[,2]
}

# divide this martix by the HDA matrix
```

```{r}
sol_HDA_26 <- matrix(nrow=6000, ncol = 351)

for (i in 1:6000) {
sol_HDA_26[i,] <- as.data.frame(lsoda(y = c(HDA_26_draws_sample$N1_0_avg[i], 
                                           HDA_26_draws_sample$N2_0_avg[i],
                                           HDA_26_draws_sample$N3_0_avg[i]),
                             times = seq(0,35, by = 0.1),
                             func = HDA_odemodel,
                             parms = c(HDA_26_draws_sample$r[i],
                                        HDA_26_draws_sample$Q[i],
                                        HDA_26_draws_sample$a1[i],
                                        5.038341e-05, #e1
                                        4.095059e+00, #d1
                                        HDA_26_draws_sample$h1[i],
                                        HDA_26_draws_sample$w1[i],
                                        9.847838e-02, #B
                                       HDA_26_draws_sample$a2[i],
                                       HDA_26_draws_sample$e2[i],
                                       HDA_26_draws_sample$d2[i],
                                       HDA_26_draws_sample$h2[i],
                                       HDA_26_draws_sample$w2[i])))[,2]

}
```

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////// CALCULATE TC STRENGTH AT EACH TIME STEP //////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

```{r}
sol_TC_14 <- sol_HDA_14/sol_DA_14

sol_TC_14 <- as.data.frame(sol_TC_14)

sol_TC_17 <- sol_HDA_17/sol_DA_17

sol_TC_17 <- as.data.frame(sol_TC_17)

sol_TC_20 <- sol_HDA_20/sol_DA_20

sol_TC_20 <- as.data.frame(sol_TC_20)

sol_TC_23 <- sol_HDA_23/sol_DA_23

sol_TC_23 <- as.data.frame(sol_TC_23)

sol_TC_26 <- sol_HDA_26/sol_DA_26

sol_TC_26 <- as.data.frame(sol_TC_26)

```


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////// SAVE TC TIME MATRICIES  //////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


```{r}
write.csv(sol_TC_14, file = "sol_TC_14_time_mat.csv")
write.csv(sol_TC_17, file = "sol_TC_17_time_mat.csv")
write.csv(sol_TC_20, file = "sol_TC_20_time_mat.csv")
write.csv(sol_TC_23, file = "sol_TC_23_time_mat.csv")
write.csv(sol_TC_26, file = "sol_TC_26_time_mat.csv")
```

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////// CALCULATE QUANTILES FROM TC TIME MATRICIES  /////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

```{r}
TC_14_iter_time <- sol_TC_14 %>%
  rownames_to_column(var = "iteration") %>%         # Add iteration column
  gather(key = "time_step", value = "TC_Strength", -iteration) %>%  # Reshape to long format
  mutate(time_step = as.numeric(gsub("V", "", time_step)))  # Clean up time_step column

```

```{r}
TC_14_iter_time_quant <- TC_14_iter_time %>%
  group_by(time_step) %>%                      # Group by time steps
  summarise(
    q2.5 = quantile(TC_Strength, 0.025),         # 2.5% quantile
    q50 = quantile(TC_Strength, 0.50),           # 50% quantile (median)
    q97.5 = quantile(TC_Strength, 0.975)         # 97.5% quantile
  )
```

```{r}
TC_17_iter_time <- sol_TC_17 %>%
  rownames_to_column(var = "iteration") %>%         # Add iteration column
  gather(key = "time_step", value = "TC_Strength", -iteration) %>%  # Reshape to long format
  mutate(time_step = as.numeric(gsub("V", "", time_step)))  # Clean up time_step column

```

```{r}
TC_17_iter_time_quant <- TC_17_iter_time %>%
  group_by(time_step) %>%                      # Group by time steps
  summarise(
    q2.5 = quantile(TC_Strength, 0.025),         # 2.5% quantile
    q50 = quantile(TC_Strength, 0.50),           # 50% quantile (median)
    q97.5 = quantile(TC_Strength, 0.975)         # 97.5% quantile
  )
```

```{r}
TC_20_iter_time <- sol_TC_20 %>%
  rownames_to_column(var = "iteration") %>%         # Add iteration column
  gather(key = "time_step", value = "TC_Strength", -iteration) %>%  # Reshape to long format
  mutate(time_step = as.numeric(gsub("V", "", time_step)))  # Clean up time_step column

```

```{r}
TC_20_iter_time_quant <- TC_20_iter_time %>%
  group_by(time_step) %>%                      # Group by time steps
  summarise(
    q2.5 = quantile(TC_Strength, 0.025),         # 2.5% quantile
    q50 = quantile(TC_Strength, 0.50),           # 50% quantile (median)
    q97.5 = quantile(TC_Strength, 0.975)         # 97.5% quantile
  )
```

```{r}
TC_23_iter_time <- sol_TC_23 %>%
  rownames_to_column(var = "iteration") %>%         # Add iteration column
  gather(key = "time_step", value = "TC_Strength", -iteration) %>%  # Reshape to long format
  mutate(time_step = as.numeric(gsub("V", "", time_step)))  # Clean up time_step column

```

```{r}
TC_23_iter_time_quant <- TC_23_iter_time %>%
  group_by(time_step) %>%                      # Group by time steps
  summarise(
    q2.5 = quantile(TC_Strength, 0.025),           # 2.5% quantile
    q50 = quantile(TC_Strength, 0.50),           # 50% quantile (median)
    q97.5 = quantile(TC_Strength, 0.975)           # 97.5% quantile
  )
```

```{r}
TC_26_iter_time <- sol_TC_26 %>%
  rownames_to_column(var = "iteration") %>%         # Add iteration column
  gather(key = "time_step", value = "TC_Strength", -iteration) %>%  # Reshape to long format
  mutate(time_step = as.numeric(gsub("V", "", time_step)))  # Clean up time_step column

```

```{r}
TC_26_iter_time_quant <- TC_26_iter_time %>%
  group_by(time_step) %>%                      # Group by time steps
  summarise(
    q2.5 = quantile(TC_Strength, 0.025),           # 2.5% quantile
    q50 = quantile(TC_Strength, 0.50),           # 50% quantile (median)
    q97.5 = quantile(TC_Strength, 0.975)           # 97.5% quantile
  )
```


```{r}
TC_14_iter_time_quant$Temp <-14
TC_17_iter_time_quant$Temp <-17
TC_20_iter_time_quant$Temp <-20
TC_23_iter_time_quant$Temp <-23
TC_26_iter_time_quant$Temp <-26
```

```{r}
TC_Full_iter_time_quant <- rbind(TC_14_iter_time_quant, TC_17_iter_time_quant, TC_20_iter_time_quant, TC_23_iter_time_quant, TC_26_iter_time_quant)
```


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////// SAVE QUANTILES FROM TC TIME MATRICIES  /////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

```{r}
write.csv(TC_Full_iter_time_quant, file = "TC_Full_iter_time_quant.csv")
```



TEST TC STRENFTH OVER TIME

```{r}
ggplot(data = TC_Full_iter_time_quant) +
  geom_line(aes(x=time_step, y=q50, color = as.factor(Temp)), linewidth = 1.5) +
  geom_ribbon(aes(x= time_step, ymin = q2.5, ymax = q97.5, color = as.factor(Temp)), alpha = 0.1) +
  geom_hline(yintercept = 1, linetype = 2, linewidth = 1.25, alpha = 0.6) +
  theme_cowplot()
```












