---
title: "TC_Strength_Plots"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(cowplot)
library(deSolve)
library(rstan)
library(coda)
library(modelbased)
library(shinystan)
library(colorspace)
library(bayesplot)
library(ggpubr)
```

LOAD IN TC TIME MATRICIES

```{r}
setwd("~/Trophic_Cascade_Warming_Submission/TC Strength")

quantiles_sol_TC_time_full <- read.csv("TC_Full_iter_time_quant.csv")

quantiles_sol_TC_time_full <- quantiles_sol_TC_time_full %>%
  mutate(Time = time_step*0.1)

Avg_TC_full <- read.csv("Avg_TC_full.csv")

```


```{r}
TC_time_plot_conf <- ggplot(data = quantiles_sol_TC_time_full) +
  geom_line(aes(x=Time, y=q50, color = as.factor(Temp)), linewidth = 1.5) +
  geom_ribbon(aes(x= Time, ymin = q2.5, ymax = q97.5, fill = as.factor(Temp)), alpha = 0.15, inherit.aes = TRUE) +
  geom_hline(yintercept = 1, linetype = 2, linewidth = 1.5, alpha = 0.6) +
  scale_color_manual("Temp (°C)", values = c("#05008F", "#125BFF", "#25FFDF", "#FEE000", "#FE6100"))+
  scale_fill_manual("Temp (°C)", values = c("#05008F", "#125BFF", "#25FFDF", "#FEE000", "#FE6100"))+
  ylim(0.5, 2.25) +
  xlab("Time (Days)") +
  ylab("Trophic Cascade Strength") +
  #scale_x_continuous(name = "Temperature °C", limits = c(17, 20, 23, 26)) +
  theme_cowplot(font_size = 24) +
  draw_label("A", x = 0, y = 2.2, hjust = 0, vjust = 1, fontface = "bold", size = 40)
```

```{r}
TC_violin <- ggplot(data = Avg_TC_full, aes(x = as.factor(Temp), y = Avg_TC, color = as.factor(Temp))) +
  geom_violin(draw_quantiles = c(0.025, 0.5, 0.975), lwd = 1.5, show.legend = FALSE) + 
  scale_color_manual("Temp (°C)", values = c("#05008F", "#125BFF", "#25FFDF", "#FEE000", "#FE6100"))+
  geom_hline(yintercept = 1, linetype = 2, linewidth = 1.5, alpha = 0.6) +
  xlab("Temperature (°C)") +
  ylab("Average Trophic Cascade Strength") +
  ylim(0.5,2.25) +
  theme_cowplot(font_size = 24) +
   draw_label("B", x = 0.5, y = 2.2, hjust = 0, vjust = 1, fontface = "bold", size = 40)
```

```{r}
TC_time_plot_conf_nodata <- ggplot(data = quantiles_sol_TC_time_full) +
  geom_line(aes(x=Time, y=q50, color = as.factor(Temp)), linewidth = 1.5, alpha = 0) +
  geom_ribbon(aes(x= Time, ymin = q2.5, ymax = q97.5, fill = as.factor(Temp)), alpha = 0, inherit.aes = TRUE) +
  #geom_blank(aes(x=Time, y=q50, color = as.factor(Temp))) +
  geom_hline(yintercept = 1, linetype = 2, linewidth = 1.5, alpha = 0.6) +
  scale_color_manual("Temp (°C)", values = c("#05008F", "#125BFF", "#25FFDF", "#FEE000", "#FE6100"))+
  scale_fill_manual("Temp (°C)", values = c("#05008F", "#125BFF", "#25FFDF", "#FEE000", "#FE6100"))+
  ylim(0.5, 2.25) +
  xlab("Time (Days)") +
  ylab("Trophic Cascade Strength") +
  theme_cowplot(font_size = 50)
```

```{r}
TC_violin_nodata <- ggplot(data = sol_TC_iter_avg_full, aes(x = as.factor(Temp), y = Avg_TC, color = as.factor(Temp))) +
  geom_blank() + 
  scale_color_manual("Temp (°C)", values = c("#05008F", "#125BFF", "#25FFDF", "#FEE000", "#FE6100")) +
  geom_hline(yintercept = 1, linetype = 2, linewidth = 3, alpha = 0.6) +
  xlab("Temperature (°C)") +
  ylab("Average Trophic Cascade Strength") +
  ylim(0.5, 2.25) +
  theme_cowplot(font_size = 50)

```

```{r}
TC_Strength_full <-  ggarrange(TC_time_plot_conf, TC_violin, ncol = 2, nrow = 1, common.legend = TRUE, align = "hv", legend = "none")

ggsave("TC_Strength_paper.png", TC_Strength_full, width = 16, height = 10, dpi = 600)
```

```{r}

TC_Strength_full_blank <-  ggarrange(TC_time_plot_conf_nodata, TC_violin_nodata, ncol = 2, nrow = 1, common.legend = TRUE, align = "hv", legend = "none")

TC_Strength_full_conf <-  ggarrange(TC_time_plot_conf, TC_violin_nodata, ncol = 2, nrow = 1, common.legend = TRUE, align = "hv", legend = "none")
```


```{r}

#ggsave("TC_Strength_present_blank.png", TC_Strength_full_blank, width = 36, height = 21, dpi = 300)

#ggsave("TC_Strength_present_violin_blank.png", TC_Strength_full_conf, width = 36, height = 21, dpi = 300)

#ggsave("TC_Strength_present_full.png", TC_Strength_full, width = 36, height = 21, dpi = 300)
```



